# Generated by Django 2.1.2 on 2018-11-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('description', models.CharField(blank=True, help_text='Request detail.', max_length=100, null=True, verbose_name='DESCRIPTION')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('content', models.TextField(verbose_name='CONTENT')),
            ],
        ),
    ]
