# Generated by Django 2.1.2 on 2018-11-06 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('individual', '0002_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='USER_NAME')),
                ('enterprise_name', models.CharField(max_length=50, verbose_name='ENTERPRISE_NAME')),
                ('additional', models.TextField(verbose_name='ADDITIONAL')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('Modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
