# Generated by Django 2.1.2 on 2018-11-06 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_blockchain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applybuffer',
            old_name='individual_id',
            new_name='indi_id',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='description',
            field=models.CharField(blank=True, help_text='simple descripton text.', max_length=100, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Request Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockchain',
            name='respond_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Respond Date'),
        ),
        migrations.AlterField(
            model_name='applybuffer',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Request Date'),
        ),
    ]
